### PR TITLE
rversions 1.1.0

### PR DESCRIPTION
**Pull request by maelle**
cf #4 + dependent on https://github.com/metacran/rversions/pull/10

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Actually, one more thing. Should we mention that this is also available as a web-service? Because R-hub and R-appveyor use the web service and not the R package.

**Comment by gaborcsardi** [comment]
The web service is updated manually, though. I wish we had an easy way to run R in a web-service. We will probably install opencpu at some point.

**Comment by maelle** [comment]
I'd be happy to add a mention of `rversions` web service no matter its setup, as long as you think it won't be problematic for its sustainability if it gets more users?

**Comment by gaborcsardi** [comment]
that's not a problem at all

**Comment by gaborcsardi** [comment]
you don't have to mention how it is updated, though, that might change anyway soon

**Comment by maelle** [comment]
What's the best URL to `rversions` web service? Is there an URL to docs?

**Comment by gaborcsardi** [comment]
no docs :)

**Comment by maelle** [comment]
but some URL I should use to link to it or none? curious folks could still look at r-appveyor/R-hub code we link to.

**Comment by gaborcsardi** [comment]
https://github.com/r-hub/rversions.app#readme

**Comment by maelle** [comment]
Ok, so now all your feedback has been taken into account, thanks! Once the docs PR is merged +  a new version is on CRAN, I can publish this I guess.

**Comment by maelle** [comment]
If https://github.com/r-hub/rversions/issues/8 happens before the CRAN release it'd be a cool thing to show in the blog post.

**Comment by maelle** [comment]
I updated the post with new version number, nickname feature (+ a link to Lucy's blog post) so now it's ready to be published on Monday/whenever the new version is released.

**Comment by gaborcsardi** [comment]
OK, Monday sounds great!

**Pull request merged**
